#!/bin/bash

#SBATCH --job-name=r010      # Job name
#SBATCH --output=/home/morah/TestTraceTradeoff/jobOutputs/job.%j.out 
#SBATCH --error=/home/morah/TestTraceTradeoff/jobOutputs/job.%j.err 
#SBATCH --cpus-per-task=8        # Schedule one core
#SBATCH --time=24:00:00     
#SBATCH --partition=scavenge    # Run on scavenge queue (all nodes, low priority)
#SBATCH --nodelist=cn9

# Print out the hostname of the node the job is running on

module load Julia

# Run the Julia script (Argument order: testwait, resultwait, Pasymp, R0, OffspringDistribution, InfectiousProfile)
JULIA_NUM_THREADS=8 julia /home/morah/TestTraceTradeoff/code/mainhpc.jl 0.0 0.0 0.3 10.0 "negativebinomial" "empirical" 
