#!/bin/bash

#SBATCH --job-name=TestTraceTradeoff        # Job name
#SBATCH --output=/home/morah/TestTraceTradeoff/jobOutputs/job.%j.out 
#SBATCH --error=/home/morah/TestTraceTradeoff/jobOutputs/job.%j.err 
#SBATCH --cpus-per-task=1        # Schedule one core
#SBATCH --nodelist=cn3
#SBATCH --time=24:00:00     
#SBATCH --partition=scavenge    # Run on scavenge queue (all nodes, low priority)

# Print out the hostname of the node the job is running on

module load Julia

# Run the Julia script (Argument order: testwait, resultwait, Pasymp, R0)
julia /home/morah/TestTraceTradeoff/code/mainhpc.jl 1.0 0.0 0.3 3.0
julia /home/morah/TestTraceTradeoff/code/mainhpc.jl 1.0 1.0 0.3 3.0
julia /home/morah/TestTraceTradeoff/code/mainhpc.jl 1.0 2.0 0.3 3.0
julia /home/morah/TestTraceTradeoff/code/mainhpc.jl 1.0 3.0 0.3 3.0
julia /home/morah/TestTraceTradeoff/code/mainhpc.jl 1.0 4.0 0.3 3.0