#!/bin/bash

#SBATCH --job-name=negativeBinomial
#SBATCH --output=/home/morah/TestTraceTradeoff/jobOutputs/job.%j.out 
#SBATCH --error=/home/morah/TestTraceTradeoff/jobOutputs/job.%j.err 
#SBATCH --cpus-per-task=9        # Update to match number of parallel jobs
#SBATCH --time=24:00:00     
#SBATCH --partition=scavenge
#SBATCH --nodelist=cn11

module load Julia

# Run Julia scripts in parallel
julia /home/morah/TestTraceTradeoff/code/mainhpc.jl 0.0 0.0 0.3 2.0 "negativebinomial" "empirical" 1 &
julia /home/morah/TestTraceTradeoff/code/mainhpc.jl 0.0 0.0 0.3 2.0 "negativebinomial" "empirical" 2 &
julia /home/morah/TestTraceTradeoff/code/mainhpc.jl 0.0 0.0 0.3 2.0 "negativebinomial" "empirical" 3 &
julia /home/morah/TestTraceTradeoff/code/mainhpc.jl 0.0 0.0 0.3 2.0 "negativebinomial" "empirical" 4 &
julia /home/morah/TestTraceTradeoff/code/mainhpc.jl 0.0 0.0 0.3 2.0 "negativebinomial" "empirical" 5 &
julia /home/morah/TestTraceTradeoff/code/mainhpc.jl 0.0 0.0 0.3 2.0 "negativebinomial" "empirical" 6 &
julia /home/morah/TestTraceTradeoff/code/mainhpc.jl 0.0 0.0 0.3 2.0 "negativebinomial" "empirical" 7 &
julia /home/morah/TestTraceTradeoff/code/mainhpc.jl 0.0 0.0 0.3 2.0 "negativebinomial" "empirical" 8 &
julia /home/morah/TestTraceTradeoff/code/mainhpc.jl 0.0 0.0 0.3 2.0 "negativebinomial" "empirical" 9 &
# Wait for all background jobs to complete
wait