#!/bin/bash

#SBATCH --job-name=r03       # Job name
#SBATCH --output=/home/morah/TestTraceTradeoff/jobOutputs/job.%j.out 
#SBATCH --error=/home/morah/TestTraceTradeoff/jobOutputs/job.%j.err 
#SBATCH --cpus-per-task=8        # Schedule one core
#SBATCH --time=24:00:00     
#SBATCH --partition=scavenge    # Run on scavenge queue (all nodes, low priority)
#SBATCH --nodelist=cn6

# Print out the hostname of the node the job is running on

module load Julia

# Run the Julia script (Argument order: testwait, resultwait, Pasymp, R0, OffspringDistribution, InfectiousProfile)
julia /home/morah/TestTraceTradeoff/code/mainhpc.jl 0.0 0.0 0.3 3.0 "negativebinomial" "empirical" 
julia /home/morah/TestTraceTradeoff/code/mainhpc.jl 1.0 0.0 0.3 3.0 "negativebinomial" "empirical" 
julia /home/morah/TestTraceTradeoff/code/mainhpc.jl 1.0 1.0 0.3 3.0 "negativebinomial" "empirical" 
julia /home/morah/TestTraceTradeoff/code/mainhpc.jl 1.0 2.0 0.3 3.0 "negativebinomial" "empirical" 
julia /home/morah/TestTraceTradeoff/code/mainhpc.jl 1.0 3.0 0.3 3.0 "negativebinomial" "empirical" 
julia /home/morah/TestTraceTradeoff/code/mainhpc.jl 1.0 4.0 0.3 3.0 "negativebinomial" "empirical" 
julia /home/morah/TestTraceTradeoff/code/mainhpc.jl 1.0 5.0 0.3 3.0 "negativebinomial" "empirical" 
julia /home/morah/TestTraceTradeoff/code/mainhpc.jl 1.0 7.0 0.3 3.0 "negativebinomial" "empirical" 
julia /home/morah/TestTraceTradeoff/code/mainhpc.jl 1.0 9.0 0.3 3.0 "negativebinomial" "empirical" 
