#!/bin/bash

#SBATCH --job-name=Se       # Job name
#SBATCH --output=/home/morah/TestTraceTradeoff/jobOutputs/job.%j.out 
#SBATCH --error=/home/morah/TestTraceTradeoff/jobOutputs/job.%j.err 
#SBATCH --cpus-per-task=8        # Schedule cores
#SBATCH --time=24:00:00     
#SBATCH --partition=scavenge    # Run on scavenge queue (all nodes, low priority)
#SBATCH --nodelist=cn16

# Print out the hostname of the node the job is running on

module load Julia

# Run the Julia script (Argument order: testwait, resultwait, Pasymp, R0, OffspringDistribution, InfectiousProfile)

JULIA_NUM_THREADS=8 julia /home/morah/TestTraceTradeoff/code/mainhpc_Se.jl 0.0 0.0 0.3 2.0 "negativebinomial" "empirical" 7

