#!/bin/bash

#SBATCH --job-name=Se_x       # Job name
#SBATCH --output=/home/morah/TestTraceTradeoff/jobOutputs/job.%j.out 
#SBATCH --error=/home/morah/TestTraceTradeoff/jobOutputs/job.%j.err 
#SBATCH --cpus-per-task=1        # Schedule one core
#SBATCH --time=24:00:00     
#SBATCH --partition=scavenge    # Run on scavenge queue (all nodes, low priority)
#SBATCH --nodelist=cn15

# Print out the hostname of the node the job is running on

module load Julia

# Run the Julia script (Argument order: testwait, resultwait, Pasymp, R0, OffspringDistribution, InfectiousProfile)

JULIA_NUM_THREADS=8 julia /home/morah/TestTraceTradeoff/code/mainhpc_Se.jl 0.0 0.0 0.3 2.0 "negativebinomial" "empirical" 
JULIA_NUM_THREADS=8 julia /home/morah/TestTraceTradeoff/code/mainhpc_Se.jl 1.0 0.0 0.3 2.0 "negativebinomial" "empirical" 
JULIA_NUM_THREADS=8 julia /home/morah/TestTraceTradeoff/code/mainhpc_Se.jl 1.0 1.0 0.3 2.0 "negativebinomial" "empirical" 
JULIA_NUM_THREADS=8 julia /home/morah/TestTraceTradeoff/code/mainhpc_Se.jl 1.0 2.0 0.3 2.0 "negativebinomial" "empirical" 
JULIA_NUM_THREADS=8 julia /home/morah/TestTraceTradeoff/code/mainhpc_Se.jl 1.0 3.0 0.3 2.0 "negativebinomial" "empirical" 
JULIA_NUM_THREADS=8 julia /home/morah/TestTraceTradeoff/code/mainhpc_Se.jl 1.0 4.0 0.3 2.0 "negativebinomial" "empirical" 
JULIA_NUM_THREADS=8 julia /home/morah/TestTraceTradeoff/code/mainhpc_Se.jl 1.0 5.0 0.3 2.0 "negativebinomial" "empirical" 
JULIA_NUM_THREADS=8 julia /home/morah/TestTraceTradeoff/code/mainhpc_Se.jl 1.0 7.0 0.3 2.0 "negativebinomial" "empirical" 
JULIA_NUM_THREADS=8 julia /home/morah/TestTraceTradeoff/code/mainhpc_Se.jl 1.0 9.0 0.3 2.0 "negativebinomial" "empirical" 
