#!/bin/bash

#SBATCH --job-name=simple        # Job name
#SBATCH --output=/home/morah/TestTraceTradeoff/jobOutputs/job.%j.out      # Name of output file (%j expands to jobId)
#SBATCH --cpus-per-task=1        # Schedule one core
#SBATCH --time=01:00:00          # Run time (hh:mm:ss) - run for one hour max
#SBATCH --partition=scavenge    # Run on scavenge queue (all nodes, low priority)

# Print out the hostname of the node the job is running on

module --ignore_cache load "Julia"

hostname

# Run the Julia script
julia /home/morah/TestTraceTradeoff/code/testscript.jl